name: Publish to MCP Registry

on:
  push:
    tags: ["v*"]

jobs:
  publish-mcp:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Node.js
        uses: actions/setup-node@v5
        with:
          node-version: "lts/*"

      - name: Sync versions between package.json and server.json
        run: node scripts/sync-versions.js

      - name: Publish to MCP Registry
        run: ./scripts/publish-mcp.sh
